### ISSUE TITLE
Create a beta release

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor4-react#10]
Before shipping 1.0.0 we'd need an explicitly marked beta release.

There should be also an information in README.md that it is a beta and we're looking for a feedback - with a link to GH issue tracker.

**Comment by jannesiera** [comment]
We are currently on `1.0.0-beta.2`. It breaks on hash based routing since the component unmounts and `destroy` is called on a null editor. This has been fixed on the master branch on 17/07.

Would it be possible to ship this fix as `1.0.0-beta.3` soon-ish?

**Comment by f1ames** [comment]
Hello @jannesiera,
we don't have such plans for now, but may reconsider if needed. Keep in mind that you can also build the package yourself from `master` branch - see https://github.com/ckeditor/ckeditor4-react#building-the-package. Have you considered building it yourself or it doesn't fit your workflow?

**Comment by jannesiera** [comment]
@f1ames thank you for the quick response.

Building it ourself would be a minor inconvenience, but possible.

I'd personally suggest doing a quick release because it really _does not work_. Since every other React app uses some form of routing, the component is currently unusable for those customers. There is already an open issue on here caused by the same thing (https://github.com/ckeditor/ckeditor4-react/issues/49). Since the sole purpose of this package is to ease the use of CKEditor from React it should at least be usable in React.

Just my 2 cents as a consumer of the product.
