### ISSUE TITLE
unable to add subscript and superscript or full version editor

### ISSUE THREAD

**Issue by Va1bhav07** [ckeditor/ckeditor4-react#101]
Hi we can only use two types (i.e) inline and classic but they have limited toolbar options how can i add full version so that i can use featues like subscript and superscript or adding colors?

**Comment by f1ames** [comment]
Please refer to [Customizing CKEditor Preset or Version](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html#customizing-ckeditor-preset-or-version) documentation section.

Please also note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave similar questions on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) next time where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
