### ISSUE TITLE
Not showing editor text if initial value of data state is empty 

### ISSUE THREAD

**Issue by ArchanaSharma95** [ckeditor/ckeditor4-react#107]
I have used "data" prop value as a state, on component load it's value is empty, after mount I am setting data value but CKEditor is not refreshed and showing empty value. On first load I am getting empty editor.

I just want to update the editor value on data state update.

This is my code::

```
class Editor extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			editorData: ''
		}
		CKEditor.editorUrl = 'https://cdn.ckeditor.com/4.14.1/full/ckeditor.js';
	}

	handleSetState(data, callback) {
		if (this.isMount) {
			this.setState(data, callback);
		}
	}

	componentDidMount() {
		this.isMount = true;
		this.handleSetState({editorData: this.props.data})
	}
	componentWillUnmount() {
		this.isMount = false;
	}
	shouldComponentUpdate(nextProps, nextState) {
		if (nextProps.data !== this.props.data) {
			this.handleSetState({editorData: nextProps.data})
		}
		return true;
	}

	onEditorChange(event) {
		let data = event.editor.getData()
		this.setState({ editorData: data }, this.props.onChange(data));
	}

	render() {
		const { editorData } = this.state;
		return (
			<CKEditor
				data={editorData}
				onChange={(e) => this.onEditorChange(e)}
			/>
		);
	}
}
```

I want to update editor text after load and also if get different value in "shouldComponentUpdate" lifecycle method.

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

**Comment by Fluorz** [comment]
+1
