### ISSUE TITLE
remove p margin tag

### ISSUE THREAD

**Issue by Roncy13** [ckeditor/ckeditor4-react#111]
Asking how to remove the p margin css in the content area?

i have tried putting contentCss in the config but it doesnt work.

![image](https://user-images.githubusercontent.com/50896886/89112907-a6675d00-d49c-11ea-9a99-bf9f51a30bea.png)

![image](https://user-images.githubusercontent.com/50896886/89112911-b3844c00-d49c-11ea-8733-be204cdaa947.png)

**Comment by Comandeer** [comment]
You can use `onBeforeLoad` property with [`CKEDITOR.addCss`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#method-addCss), e.g.

```jsx
<CKEditor onBeforeLoad={ () =>CKEDITOR.addCss( '.cke_editable, .cke_editable p { margin: 0; }' ) } />
```

Please also note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
