### ISSUE TITLE
Can't add @wiris/mathtype-ckeditor4 as an external plugin.

### ISSUE THREAD

**Issue by henok-tesfaye** [ckeditor/ckeditor4-react#117]
## Type of report
I'm trying to add wiris as an extra plugin following https://www.npmjs.com/package/@wiris/mathtype-ckeditor4#install-instructions to get the latest fix (https://github.com/ckeditor/ckeditor4/issues/3817).

```
export const addWirisPlugin = CKEDITOR => {
  CKEDITOR.plugins.addExternal('ckeditor_wiris', '../../../node_modules/@wiris/mathtype-ckeditor4/', 'plugin.js')
}
```
`Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "ckeditor_wiris" was not found at "https://cdn.ckeditor.com/4.14.0/full-all/../../../node_modules/@wiris/mathtype-ckeditor4/plugin.js?t=K24B".
`
I'm getting this error, I think the path is concatenated with `https://cdn.ckeditor.com/4.14.0/full-all` and caused the error.
How can I add locally installed wiris plugin as external plugin?

<img width="1565" alt="Screen Shot 2020-08-31 at 7 48 17 PM" src="https://user-images.githubusercontent.com/51118408/91745003-fd0ea680-ebc2-11ea-80c6-1a07791d5009.png">

### Expected result
CKEditor with wiris mathtype plugin should be displayed.
*What is the expected result of the above steps?*

### Actual result
`Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "ckeditor_wiris" was not found at "https://cdn.ckeditor.com/4.14.0/full-all/../../../node_modules/@wiris/mathtype-ckeditor4/plugin.js?t=K24B".
`
*What is the actual result of the above steps?*

## Other details

* Browser: Chrome
* OS: OSX
* CKEditor version: 4.14
* Installed CKEditor plugins: @wiris/mathtype-ckeditor4

**Comment by Dumluregn** [comment]
You should probably use the absolute path in such case. Also, please keep in mind my previous comment:

> please note that our GitHub issue tracker serves for reporting bugs and new features only.

**Comment by henok-tesfaye** [comment]
Yes, I asked in StackOverflow. https://stackoverflow.com/questions/63702343/cant-add-mathtype-plugin-locally-in-ckeditor.
I'll add a comment there how to use an absolute path. Thanks!

**Comment by f1ames** [comment]
Hello @henok-tesfaye,

I have taken a look on this issue and another one you reported related to React CRA (#118) since the cause (and solutions) are the same here. And so...

The [`CKEDITOR.plugins.addExternal`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins.html#method-addExternal) method which loads external plugins is based on [`CKEDITOR.getUrl`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#method-getUrl) to resolve resources URLs. The `CKEDITOR.getUrl` itself resolves passed URLs in different ways depending if it's treated as full/absolute or relative URL.

**The relative URLs** are resolved to full domain (from which CKEditor 4 was loaded). It can also be modified via [`CKEDITOR_BASEPATH`](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_basepath.html#solution-ckeditor_basepath) (see also this [SO answer](https://stackoverflow.com/a/36083620/646871)), but it won't help in this case as it affects all editor resources (so after changing it, editor will try to load CDN resources from your local path/URL).

**The full/absolute URLs** are simply left untouched which means that they will be resolved by the browser related to the current URL (not the one from which editor was loaded if it's different).

Let's assume that your web app URL (where CKEditor 4 is loaded) is `http://localhost:8080` and CKEditor 4 itself was loaded from CDN as you mentioned (e.g. `https://cdn.ckeditor.com/4.14.1/full-all/ckeditor.js`). You can now pass WIRIS plugin path in 4 different ways:

```js
console.log( CKEDITOR.getUrl( './node_modules/@wiris/mathtype-ckeditor4/plugin.js' ) );
// Resolves to https://cdn.ckeditor.com/4.14.1/full-all/./node_modules/@wiris/mathtype-ckeditor4/plugin.js?t=K5H9

console.log( CKEDITOR.getUrl( 'node_modules/@wiris/mathtype-ckeditor4/plugin.js' ) );
// Resolves to https://cdn.ckeditor.com/4.14.1/full-all/node_modules/@wiris/mathtype-ckeditor4/plugin.js?t=K5H9

console.log( CKEDITOR.getUrl( '/node_modules/@wiris/mathtype-ckeditor4/plugin.js' ) );
// Absolute URL (due to / on the beginning), resolves to '/node_modules/@wiris/mathtype-ckeditor4/plugin.js'

console.log( CKEDITOR.getUrl( 'http://localhost:8080/node_modules/@wiris/mathtype-ckeditor4/plugin.js' ) );
// Full absolute path, resolves to 'http://localhost:8080/node_modules/@wiris/mathtype-ckeditor4/plugin.js'
```

As using full absolut path is not very flexible (since you have domain hardcoded), in your case the best option would be to go with path like `/node_modules/@wiris/mathtype-ckeditor4/plugin.js` (so adding `/` at the beginning of your path):

```js
export const addWirisPlugin = CKEDITOR => {
  CKEDITOR.plugins.addExternal('ckeditor_wiris', '/../../../node_modules/@wiris/mathtype-ckeditor4/', 'plugin.js')
}
```

**Comment by henok-tesfaye** [comment]
Awesome thank you @f1ames for the detailed explanation.

The error is now changed from `'ckeditor_wiris' was not found at ..` to `Uncaught SyntaxError: Unexpected token '<' Uncaught TypeError: Cannot read property 'icons' of null
`.

<img width="1680" alt="Screen Shot 2020-09-04 at 2 12 32 PM" src="https://user-images.githubusercontent.com/51118408/92233666-5fb0bc80-eeb9-11ea-9f7b-6a75d6708a69.png">

**Comment by f1ames** [comment]
@henok-tesfaye have you tested it locally or on `codesandbox`? From what I see `codesandbox` has some issue with loading `node_modules` files in such way and it simply returns HTML page which causes this error:

![](https://user-images.githubusercontent.com/1061942/92234353-304a8180-eeb2-11ea-9706-7440c5de8be1.png)

It will work only if the `plugin.js` file is available under the given, local URL.

**Comment by henok-tesfaye** [comment]
@f1ames I tried it in both locally and sandbox.
I'm getting html response too in local setup.

<img width="1680" alt="Screen Shot 2020-09-04 at 2 31 20 PM" src="https://user-images.githubusercontent.com/51118408/92234799-5a547180-eebb-11ea-9f08-472cec52b0cb.png">

**Comment by henok-tesfaye** [comment]
@f1ames I think the issue is accessing `plugin.js` inside `node_modues` folder using url(http://localhost:3000/node_modules/@wiris/mathtype-ckeditor4/plugin.js) may be related with `webpack`. 

When I copy `mathtype-ckeditor4` from `node_modules/@wiris` to `public` folder and access it like,

```
CKEDITOR.plugins.addExternal(
  'ckeditor_wiris',
  '/mathtype-ckeditor4/',
  'plugin.js'
)
```
It will work, however I don't think this is the preferred approach. Thanks!

**Comment by f1ames** [comment]
Hi @henok-tesfaye,

> @f1ames I tried it in both locally and sandbox.  
> I'm getting html response too in local setup.

Yes, you are right here, I assumed it was `codesandbox` issue while in fact it's webpack configuration which doesn't expose plugin files as you mentioned in https://github.com/ckeditor/ckeditor4-react/issues/117#issuecomment-687100372.

> It will work, however I don't think this is the preferred approach. Thanks!

Well, since it is not bundled into CKEditor 4 directly, you need a way to expose it in you application so CKEditor can load it. So I think it's a valid approach. Ofc, the most convenient solution should just use webpack to move `mathtype` plugin assets (files which will be used only) to your public folder during build so you don't have to do it manually.

**Comment by henok-tesfaye** [comment]
Awesome, thank you @f1ames .
