### ISSUE TITLE
How can I add "Tags" select list like "Format" added to use custom tokens inside my content?

### ISSUE THREAD

**Issue by ArchanaSharma95** [ckeditor/ckeditor4-react#128]
I am using this to set email content. Now I want to add custom token select list inside toolbar to use predefined token. How to add custom select list inside toolbar?

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
