### ISSUE TITLE
ckEDitor4 react custom build issue

### ISSUE THREAD

**Issue by monika1111** [ckeditor/ckeditor4-react#143]
I want to have a custom build in my local as I want to add my custom plugin to ckeditor4-react plugins.  

I have download my custom version of ckEditor from here https://ckeditor.com/cke4/builder, and following from this guide https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html#customizing-ckeditor-preset-or-version I have set the CKEditor.editorUrl like

 `CKEditor.editorUrl = "../../plugins/ckeditor.js";` to my local ckEditor4 path

![image](https://user-images.githubusercontent.com/16905883/98085531-e3296280-1e96-11eb-8227-ce466dccd82d.png),

 but I got an error like this 

![image](https://user-images.githubusercontent.com/16905883/98085726-2c79b200-1e97-11eb-918c-4097a4a508d2.png).

 Can please tell me why?

Thanks

**Comment by Comandeer** [comment]
It seems that you have ESLint configured to also lint the code of CKEditor4, which cause the errors you shown. You probably need to change the configuration of ESLint to ignore the directory with CKEditor 4.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
