### ISSUE TITLE
Autocomplete plugin add

### ISSUE THREAD

**Issue by psdevu** [ckeditor/ckeditor4-react#153]
How I can add an autocomplete plugin in CKEditor in react

**Comment by f1ames** [comment]
Hi @psdevu,

Please tak a look at [React documentation](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html#changing-the-editor-configuration) and [`extraPlugins` configuration](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-extraPlugins).

Please also note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave similar questions on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) next time where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
