### ISSUE TITLE
Getting error when hosting on IIS and a subdirectory in localhost

### ISSUE THREAD

**Issue by KrishnaPrasanthVemuganti** [ckeditor/ckeditor4-react#176]
Getting error when hosting on IIS and a subdirectory in localhost (http:/localhost/reactApp)  and whole application is not loading(getting a blank screen)

![image](https://user-images.githubusercontent.com/10269705/110159141-ec2c3100-7daf-11eb-9124-74199624395d.png)

Code usage of CKEditor:

```
import React from "react";
import CKEditor from "ckeditor4-react";

const Email = () => {
	return <CKEditor data="<p>Hello from CKEditor 4!</p>" />;
};

export default Email;
```

Tried adding the base path as well in a `basepath.js` and importing into above component:
```
window.CKEDITOR_BASEPATH =
	process.env.REACT_APP_BASE_URL + "/node_modules/ckeditor4-react/";
```

Please suggest any other changes required... 

_same code is working fine when running as self hosted app (http:/localhost:8090)_

**Comment by sculpt0r** [comment]
Hi @KrishnaPrasanthVemuganti 

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
