### ISSUE TITLE
Support Consumption of Non-Webpacked Source Code

### ISSUE THREAD

**Issue by sbulley09** [ckeditor/ckeditor4-react#180]
## Are you reporting a feature request or a bug?
Feature Request

## Request Details
Currently, the only method of consumption is via the webpacked bundle in the dist folder. This webpack bundle includes a polyfill babel polyfill set up via the usage method. This ends up adding a polyfill for Promises but not for the 'finally' functionality of promises since those are not used within the code. One of our solutions relies on a promise polyfill which is a different polyfill than the provided by babel. 

Since the incomplete babel polyfill is loaded first without all the functionality, it doesn't get overwritten by our polypill and thus we end up with the 'finally' functionality missing. As a work around, we've copied the source code into our own project which allows us to use our internal strategy of building projects. This comes with the downside of having to continually update our internal fork over time and maintain that ourselves. It would be ideal for us to be able to consume the non-webpacked source and be able to apply our own polyfills as needed.

**Comment by sculpt0r** [comment]
@sbulley09 , @ryanthemanuel   
I talked with @f1ames and we decide to reopen this feature request and take it into a schedule.

**Comment by MMMalik** [comment]
We can simply publish `src` folder along `dist`. Then consumers can do pretty much whatever they want with it. Alternatively, since our component is a fairly typical esm module, we can copy it to `dist` and expose it via `module` or `esnext` field on `package.json` but I'm not sure it's a fully backward compatible solution (Some existing setups might break? Will `webpack` default to `module` instead if `main`?).

**Comment by f1ames** [comment]
> We can simply publish `src` folder along `dist`. Then consumers can do pretty much whatever they want with it.

We were thinking about such solution. Theoretically, one can simply use GitHub repo with `stable` branch to get latest dev version. OTOH it would be more convenient to have it in npm module. 

>  Alternatively, since our component is a fairly typical esm module, we can copy it to `dist` and expose it via `module` or `esnext` field on `package.json` but I'm not sure it's a fully backward compatible solution (Some existing setups might break? Will `webpack` default to `module` instead if `main`?).

I guess this would be more "proper" solution so it can be consumed easier as it's integrated into standard workflows. Not sure about backwards compatibility and `webpack` though :thinking: @Comandeer WDYT?

**Comment by f1ames** [comment]
Hi @sbulley09 and @ryanthemanuel,

This is already covered in new RC version available [already on NPM](https://www.npmjs.com/package/ckeditor4-react). Feel free to check how it works - your feedback on this is more than welcome. You can find documentation on a new version [here](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react_v2.html).

**Comment by f1ames** [comment]
Hi @sbulley09 and @ryanthemanuel,

The RC version previously mentioned in https://github.com/ckeditor/ckeditor4-react/issues/180#issuecomment-878346617 has been released as `stable` `2.0.0` version today so you can use it for production.

Fixed in `2.0.0` version (https://github.com/ckeditor/ckeditor4-react/commit/f03dde821f2d5b62d46c4a2e80345aae2d7f39f0 and https://www.npmjs.com/package/ckeditor4-react/v/2.0.0).
