### ISSUE TITLE
how can I add placeholder text in ckedit4 react , please guide

### ISSUE THREAD

**Issue by assdi54** [ckeditor/ckeditor4-react#212]

**Comment by sculpt0r** [comment]
Hi, @assdi54,
Please take a look at [placeholder config](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-editorplaceholder) and how to use config with [react integration](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html#config).

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

**Comment by assdi54** [comment]
Is there way to add html Markup in editorPlaceHolder ? @sculpt0r
