### ISSUE TITLE
Error: Script loaded from editorUrl doesn't provide CKEDITOR namespace.

### ISSUE THREAD

**Issue by moc89** [ckeditor/ckeditor4-react#234]
## Are you reporting a feature request or a bug?
BUG

## Provide detailed reproduction steps (if any)
All I need to use a plugin ('lite') that is not support by CDN. 

I downloaded the custom package from the online builder but I had the error described below. 
I also tried to download the standard package and copied the content of the zip (ckeditor folder) under src/assets/ in order to have everything in local (not from CDN).

1. I downloaded the custom package from online builder.
2. I added to my assest/script folder under react solution.
3. I set  editorUrl to '../assets/scripts/ckeditor4/ckeditor.js' .

*What is the expected result of the above steps?*
I expect that It should work properly, but I get a console error below;
### Actual result

![image](https://user-images.githubusercontent.com/3018351/124599072-2dffdd80-de5d-11eb-80d5-4438a4247040.png)

## Other details

* Browser: Chrome
* OS: Windows
* Integration version: None
* CKEditor version: ckeditor_4.16.1_standard
* Installed CKEditor plugins: I use default plugins. ( But I will need 'lite' plugin in the future )

**Comment by Comandeer** [comment]
You can see a sample usage of `editorUrl` with custom value in #236.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

**Comment by MMMalik** [comment]
Hi @moc89, it looks like there is an issue with the value you are using for `editorUrl`. By looking at the screenshot, I suspect that your `../assets/scripts/ckeditor4/ckeditor.js` most likely points to a non-existing resource. Instead of `ckeditor.js`, a default `html` file is returned by your server (see `Unexpected token '<'` line).

**Comment by moc89** [comment]
Hi @Comandeer and @MMMalik, 
Thanks for your answers. The problem was about URL as @MMMalik said. 

Because I use react-router for routing path for the project. When I give a path to `editorUrl`, it's not loading ckeditor.js. 
And I found a workaround for now and I put ckeditor to another server and give that path to the `editorUrl`. 

Cheers
Onur
