### ISSUE TITLE
CKEditor CDN is down

### ISSUE THREAD

**Issue by neutraali** [ckeditor/ckeditor4-react#253]
The CDN is down. As you might expect, this crashes most editor instances.

`Error: Failed to load https://cdn.ckeditor.com/4.16.2/standard-all/ckeditor.js`

Navigating to `https://cdn.ckeditor.com/` triggers `net::ERR_NAME_NOT_RESOLVED`.

Now would be a good time for tips on how to set up a local **CKEditor React** environment...

**Comment by MMMalik** [comment]
Hello @neutraali,

I don't have any troubles accessing [CDN](https://cdn.ckeditor.com/4.16.2/standard-all/ckeditor.js). Perhaps it's a DNS issue on your end?

> Now would be a good time for tips on how to set up a local CKEditor React environment...

There is already a minimal working example [here](https://github.com/ckeditor/ckeditor4-react/tree/master/samples/editor-url).

This being said, please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on Stack Overflow where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at Stack Overflow.
