### ISSUE TITLE
file upload can rename upload property? I didn't find a way!!

### ISSUE THREAD

**Issue by zhilianghuang** [ckeditor/ckeditor4-react#26]
![image](https://user-images.githubusercontent.com/17289763/55679427-0e0ba780-593e-11e9-873d-7c075679ddc0.png)

**Comment by Comandeer** [comment]
Please note that this repository is dedicated for issues connected with CKEditor 4 React integration and your question is about CKEditor 4 in general.

Additionally please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
