### ISSUE TITLE
editorUrl prop weird behaviour

### ISSUE THREAD

**Issue by daniel-MELI** [ckeditor/ckeditor4-react#278]
## Are you reporting a feature request or a bug?

Bug / Other

## Provide detailed reproduction steps (if any)

how should the editorUrl prop work?

the documentation says that by default the React editor loads the latest CKEditor from the CDN. It also says that the behavior can be altered by using the editorUrl prop to point to the script location.

So, I have a ckeditor js script on my website CDN but when I use it on the CKEditor it fails because the js library is asking for dependencies (js, css, others). Is this a normal behaviour? what's the point on having a js library on my website if those dependencies are trying to solve on my website as well? How many files are required on the initial load?

Regards

## Other details

* CKEditor version: 4

**Comment by MMMalik** [comment]
Hello @daniel-MELI,

please take a look at our [editor-url](https://github.com/ckeditor/ckeditor4-react/tree/master/samples/editor-url) sample for more guidance. Basically, `ckeditor4` package can be installed from NPM like any other dependency and then during build step **all** editor assets must be copied to the desired location. Only then the entry file can be referenced  via `editorUrl`.

This being said, please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on Stack Overflow where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at Stack Overflow.
