### ISSUE TITLE
HTML text not viewed using CKeditor version 4

### ISSUE THREAD

**Issue by sreejithkalarikkal** [ckeditor/ckeditor4-react#295]
## Are you reporting a feature request or a bug?
Bug

I am doing a project using React admin and have a requirement to preview the HTML as actual text and to edit the text and need to save as HTML.
I am using  CKEditor version 4 to preview  the code source as HTML .
The HTML is taking from the database and I set this to a variable and tried to display to on CKEditor  using  initData property.
but it shows a blank screen.
I tried hardcoding the same HTML into initData property then it found working.
![Two](https://user-images.githubusercontent.com/112066079/202163215-835a310e-da7e-4ab0-9e95-0c7a906a8974.jpg)

## Provide detailed reproduction steps (if any)

1.I have a list of HTML values from that I am selecting one HTML template from database 
  
2.The value of   initData is taking from database as string  as HTML and is assigned to initData
  initdata ={getXXXXX}
3.The data is not displayed in the CKeditor 

### Expected result

I expect  the actual result of the  passesd HTML string 

### Actual result
CKeditor  shows a blank screen
![One](https://user-images.githubusercontent.com/112066079/202159527-c6ad19df-e74a-48da-8849-b9b2c27d610d.png)

## Other details

* Browser: … Google chrome
* OS: … Windows 11
* Integration version: …
* CKEditor version: …4.1.0
* Installed CKEditor plugins: …ckeditor4": 4.20.0

**Comment by KarolDawidziuk** [comment]
Hello @sreejithkalarikkal 

It is worth checking if the received data from the database is ready before initializing the editor.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

**Comment by maulayyacyber** [comment]
same the issue
