### ISSUE TITLE
Uncaught TypeError: (p.templates || "default").split is not a function

### ISSUE THREAD

**Issue by 5ud03r5** [ckeditor/ckeditor4-react#296]
Im using react 18 with ckeditor4-react in current (4.1.1) version.
I loaded extraPlugins 'templates' and i see that button is visible on toolbar but i cant see any templates inside.

<CKEditor
              onChange={onChangeTextHandler}
              
              config={{
                extraPlugins: "templates",
                height: 500,
                templates: [
                  {
                    title: "My template",
                    image: "",
                    description: "asdasdasdasd",
                    html: "<h1>My template</h1>",
                  },
                  {
                    title: "My template 2",
                    image: "",
                    description: "asdasdasd",
                    html: "<h1>My template 2</h1>",
                  },
                ],
              }}
            />

Any ideas how can that be fixed?

**Comment by KarolDawidziuk** [comment]
Hi @5ud03r5 

In the CKEditor 4 documentation, there is a guide on [how to define Content Templates](https://ckeditor.com/docs/ckeditor4/latest/features/templates.html#defining-templates), please check it.

Also, please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
