### ISSUE TITLE
Get ckeditor4 onhover event

### ISSUE THREAD

**Issue by codeforsure** [ckeditor/ckeditor4-react#55]
I want to know whether the ckeditor supports the following features ,If it supports how to do it

1.Can we give a popup onHover on any of the ckeditor buttons

2. can we add additional text in the dialog box that appears when we click any ckeditor button

**Comment by f1ames** [comment]
Hello @codeforsure,
this issue is not directly related to React integration but to CKEditor 4 itself. As already suggested in https://github.com/ckeditor/ckeditor-dev/issues/3289#issuecomment-513724671 please refer to online resources like [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) when looking for the answer.
