### ISSUE TITLE
I set "align" in toolbarGroups, but it does't work and does't exist on toolbar, how need I do

### ISSUE THREAD

**Issue by guiyu1230** [ckeditor/ckeditor4-react#69]
`
toolbarGroups: [
         { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi', 'paragraph' ] },
  ],
`
I set "align" ,   bug it don't work and no't exist on toolbar,  so does "bidi" , How need I do

**Comment by f1ames** [comment]
Hello @guiyu1230,
please take a look on the Toolbar Configurator - http://cdn.ckeditor.com/4.13.0/full-all/samples/toolbarconfigurator/index.html#basic, this should help you get correct values or just entire toolbar config.

**Comment by indefinitelee** [comment]
Hi, I'm having the same issue. Here's the setup in codesandbox
https://codesandbox.io/s/smoosh-cherry-gdcf6

align, bigi, font color, background color, font, and font size are not appearing. 
Please let me know how I can resolve. 

thanks

**Comment by f1ames** [comment]
Hello @indefinitelee,
thanks for sharing code sample, now I see where the problem is.

Since the default preset loaded by the React integration is `standard-all` preset which means all plugins are available but only those used in [`standard` presets](https://ckeditor.com/docs/ckeditor4/latest/examples/standardpreset.html) are loaded, you have to add any additional plugins you would like to use via [`extraPlugins` config](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-extraPlugins):

```js
extraPlugins: "justify,font,colorbutton",
```

so in your example:
* align needs `justify` plugin
* font and fontsize needs `font` plugin
* colors needs `colorbutton` plugin (and optionally `colordialog` plugin to add colorpicker dialog)

Please see updated code sample - https://codesandbox.io/s/boring-moon-xfr27.

**Comment by indefinitelee** [comment]
@f1ames  looks to be working thanks!
