### ISSUE TITLE
Set max-size limit while uploading image

### ISSUE THREAD

**Issue by codeforsure** [ckeditor/ckeditor4-react#90]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)
 I was trying to restrict max-upload size of the image using this code 
```
const onFileUploadRequest = evt => {
  let fileLoader = evt.data.fileLoader;
  if (fileLoader.file.size > max_size) {
     fileLoader.abort ();
    evt.cancel ();
  } else {
    //DO required
    // To prevent the default behavior.
    evt.stop ();
  }
};
```

### Expected result

Should not show any message and restrict files above maximum size

### Actual result

showing a alert message with undefined text after calling fileLoader.abort() function

**Comment by jacekbogdanski** [comment]
Hello @codeforsure,

this issue doesn't seem to be related to the React integration itself, but CKEditor 4. Please, if you see that the issue is caused by the editor, not your implementation, report the issue at https://github.com/ckeditor/ckeditor4

Albeit, note that our issue tracker is used for reporting bugs and features only, so if you have some implementation issue, please leave your question at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor) where community and our team helps with editor customizations.

**Comment by codeforsure** [comment]
Thanks @jacekbogdanski, I reported the same issue at https://github.com/ckeditor/ckeditor4. I also tagged the same issue on stackoverflow as well.
