### ISSUE TITLE
Clicking "maximize" and then hitting the back button

### ISSUE THREAD

**Issue by ateunis-ae** [ckeditor/ckeditor4-react#92]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Click the maximize toolbar button once to view in full screen mode (do not click it again)
2. Click the back button on the browser

### Expected result

When you hit the back button, the top level `<div>` elements that ckeditor manipulates return to normal. This includes all the original classes coming back.

### Actual result

The top level `<div>` elements of your webpage remain manipulated with inline styles and the classes do not return.

## Other details

I am using a SPA with react router, so hitting the back button does not refresh the page. This bug was likely missed because hitting the back button normally refreshes the page on a typical webpage, meaning the original HTML comes back intact.

**Comment by f1ames** [comment]
Hello @ateunis-ae,

keep in mind that CKEditor 4 features are not integrated with browser history and it is intentional behavior to not mess up with regular history flow (especially for regular websites). This means it is up to developer to integrate features like maximize with browser history.

There is an [`maximize` event](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#event-maximize) fired every time editor is maximized (both ways). To change maximized state of the editor you just need to run [`editor.execCommand( 'maximize' )`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-execCommand) - it should be probably done in a react router before route is changed to solve your issue.
