### ISSUE TITLE
Upload Image in React and Node JS 

### ISSUE THREAD

**Issue by chuksgpfr** [ckeditor/ckeditor4-react#95]
I can't upload images from ckeditor4-react to my node.js backend. i keep getting

HTTP error occurred during file upload (404: File not found)

My code below 👍 
`<CKEditor
                                                    data="<p>Hello from CKEditor 4!</p>"
                                                    config={{
                                                        filebrowserBrowseUrl : 'http://localhost:2850/api/uploadimage',
                                                        filebrowserUploadUrl : '/uploader/browseimage'
                                                    }}
                                                />`

mt node.js backend is 

`
route.post('/uploadimage',verifyToken, (req,res)=>{
    console.log('uploading')
    //jwt.verify(req.token, 'tokensecret', (err, decoded)=> {
        
        // if(err){
        //     throw err;
        // }else{
            //let {email} = decoded.payload;
            res.json('ok')
        //}

      //});
});`

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
