### ISSUE TITLE
Add mathtype plugin

### ISSUE THREAD

**Issue by henok-tesfaye** [ckeditor/ckeditor4-react#96]
## Are you reporting a feature request or a bug?
An issue while integrating mathtype to react 

## Provide detailed reproduction steps (if any)

1. Install ckeditor4-react 
2. Install https://www.npmjs.com/package/@wiris/mathtype-ckeditor4

### Expected result
I want to see the mathtype icon in the ckeditor
*What is the expected result of the above steps?*

* Browser: …
* OS: …
* Integration version: …
* CKEditor version: 4
* Installed CKEditor plugins: https://www.npmjs.com/package/@wiris/mathtype-ckeditor4

I downloaded  and used `ckeditor4-react` locally and add mathtype following the documentation, in `ckeditor.jsx` 

```
    CKEDITOR.plugins.addExternal('ckeditor_wiris', '../../node_modules/@wiris/mathtype-ckeditor4/', 'plugin.js')
    CKEDITOR.replace('editor1', {
       extraPlugins: 'ckeditor_wiris'
     })
```

```
import React from "react";
import CKEditor from ./'ckeditor4-react'
import "./styles.css";

export default function App() {
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
      <CKEditor
        data="<p> Hello From CKEDitor4"
      />
    </div>
  );
}

```

Mathtype icon is not displayed in the editor.
1. `[CKEDITOR] Error code: editor-incorrect-element. {element: "editor1"}`, I noticed that the `div` doesn't have an id and name editor1 and I added that in `ckeditor.jsx` but I found `[CKEDITOR] Error code: editor-element-conflict. {editorName: "editor1"}` error. When I changed `replace` to `replaceAll`, it doesn't show an error but mathtype icon is not displayed in the toolbar.

```
      CKEDITOR.replaceAll({
        extraPlugins: 'ckeditor_wiris'
      })
```

**Comment by jacekbogdanski** [comment]
I have no problem including mathtype plugin with react integration, so it seems like there is a problem with your configuration:

![image](https://user-images.githubusercontent.com/10279586/82987279-91330580-9ff7-11ea-9170-b7a098fab9bf.png)

Note that [CKEDITOR.plugins.addExternal](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins.html#method-addExternal) adds resources **relative to the editor package**. It means that if you are using the editor with default CDN link and mathtype plugin via npm package, it won't work as the editor package exists in a different place and it's trying to resolve resource path relative to CDN link.

As a quick workaround, you could just install both the editor and mathtype plugin using npm:

```html
<script src="../node_modules/ckeditor4/ckeditor.js"></script>
<script>
  CKEDITOR.plugins.addExternal( 'ckeditor_wiris', '/node_modules/@wiris/mathtype-ckeditor4/', 'plugin.js' );
</script>
```

Note the code above must be executed before react component - otherwise it will try to resolve editor namespace on its own, and this code won't produce any effect.
